### ISSUE TITLE
Checklist for next release

### ISSUE THREAD

**Issue by gRegorLove** [indieweb/indieauth-client-php#20]
- [x] review and merge #19 
- [x] review [Changes from 26 November 2020 to this version](https://indieauth.spec.indieweb.org/#changes-from-26-november-2020-to-this-version) to see if there's anything else we should add
  - [x] add discoverRevocationEndpoint, discoverIntrospectionEndpoint, and
discoverUserinfoEndpoint methods
- [x] review and merge #22 (to run unit tests)
- [x] update README to detail new methods (included in #24)
- [x] update/syncrhonize version number and github tags
  - [x] next version 1.1.6 unless any breaking changes introduced
  - [x] [packagist release](https://packagist.org/packages/indieauth/client) is 1.1.5 
  - [x] [VERSION constant](https://github.com/indieweb/indieauth-client-php/blob/main/src/IndieAuth/Client.php#L5) is 1.1.4
  - [x] latest github release is 1.0.1 tag
- [x] ensure [milestone 1.1.6](https://github.com/indieweb/indieauth-client-php/milestone/1) is complete
